name: ukraine-salt-cavern
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  
  # Core geospatial libraries
  - geopandas>=0.12.0
  - shapely>=1.8.0
  - fiona>=1.8.0
  - rasterio>=1.3.0
  - gdal>=3.4.0
  - pyproj>=3.3.0
  
  # Data analysis
  - pandas>=1.4.0
  - numpy>=1.21.0
  
  # Image processing
  - opencv>=4.6.0
  
  # Additional utilities
  - pathlib2
  
  # For visualization (optional)
  - matplotlib>=3.5.0
  
  # Pip dependencies
  - pip
  - pip:
    - Pillow>=8.0.0
    - opencv-python>=4.6.0
